export const FETCH_OPTIONS_DATA = "FETCH_OPTIONS_DATA"

export const UPDATE_BOOKING_FIRST_NAME = "UPDATE_BOOKING_FIRST_NAME"
export const UPDATE_BOOKING_LAST_NAME = "UPDATE_BOOKING_LAST_NAME"
export const UPDATE_BOOKING_EMAIL = "UPDATE_BOOKING_EMAIL"
export const UPDATE_BOOKING_PHONE = "UPDATE_BOOKING_PHONE"
export const UPDATE_BOOKING_CONTENT = "UPDATE_BOOKING_CONTENT"
export const UPDATE_BOOKING_OPTION_ID = "UPDATE_BOOKING_OPTION_ID"
export const UPDATE_BOOKING_DATETIME = "UPDATE_BOOKING_DATETIME"
